In [1]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [3]:
#2. Print the NUMPY version and the configuration.
print(np.version.version)

1.15.4


In [14]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

a = np.random.random((2,3,5))

In [15]:
#4. Print a.
print(a)

[[[0.83513348 0.37693289 0.81594119 0.69758533 0.11003698]
  [0.39703178 0.21331075 0.38279216 0.50700705 0.09624282]
  [0.54364982 0.32438977 0.59623947 0.42755506 0.40017937]]

 [[0.84184994 0.26660777 0.1156732  0.32873476 0.60208098]
  [0.6826124  0.39875683 0.95053918 0.74991048 0.17634668]
  [0.05229202 0.11221816 0.5596292  0.49960154 0.58535413]]]


In [16]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b = np.random.random((5,2,3))

In [17]:
#6. Print b.
print(b)

[[[0.58398433 0.60339464 0.83791019]
  [0.30611888 0.39692493 0.36027191]]

 [[0.72901362 0.32133832 0.02074842]
  [0.96719068 0.100707   0.31709846]]

 [[0.36789235 0.31342537 0.18430965]
  [0.0394117  0.98421258 0.00905978]]

 [[0.81634011 0.03854645 0.6688864 ]
  [0.16311583 0.10660487 0.86117173]]

 [[0.05591802 0.7481566  0.39095038]
  [0.69250919 0.63434301 0.24541266]]]


In [18]:
#7. Do a and b have the same size? How do you prove that in Python code?
a.size == b.size

True

In [19]:
#8. Are you able to add a and b? Why or why not?
print(a+b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [34]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c = b.transpose(1,2,0)
print(a.shape)
print(c.shape)

(2, 3, 5)
(2, 3, 5)


In [36]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d = a + c
print(d)
print("The arrays now have the same shape, so Python ")

[[[1.4191178  1.10594651 1.18383354 1.51392544 0.165955  ]
  [1.00042642 0.53464907 0.69621753 0.5455535  0.84439942]
  [1.38156    0.3451382  0.78054912 1.09644146 0.79112975]]

 [[1.14796882 1.23379846 0.15508491 0.49185059 1.29459017]
  [1.07953733 0.49946383 1.93475177 0.85651534 0.8106897 ]
  [0.41256394 0.42931662 0.56868898 1.36077327 0.83076679]]]
The arrays now have the same shape, so Python 


In [39]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print (a)
print (d)
print("arr d contains arr a plus arr c")
print("d = a + c")

[[[0.83513348 0.37693289 0.81594119 0.69758533 0.11003698]
  [0.39703178 0.21331075 0.38279216 0.50700705 0.09624282]
  [0.54364982 0.32438977 0.59623947 0.42755506 0.40017937]]

 [[0.84184994 0.26660777 0.1156732  0.32873476 0.60208098]
  [0.6826124  0.39875683 0.95053918 0.74991048 0.17634668]
  [0.05229202 0.11221816 0.5596292  0.49960154 0.58535413]]]
[[[1.4191178  1.10594651 1.18383354 1.51392544 0.165955  ]
  [1.00042642 0.53464907 0.69621753 0.5455535  0.84439942]
  [1.38156    0.3451382  0.78054912 1.09644146 0.79112975]]

 [[1.14796882 1.23379846 0.15508491 0.49185059 1.29459017]
  [1.07953733 0.49946383 1.93475177 0.85651534 0.8106897 ]
  [0.41256394 0.42931662 0.56868898 1.36077327 0.83076679]]]
arr d contains arr a plus arr c
d = a + c


In [40]:
#12. Multiply a and c. Assign the result to e.
e = a * c

In [41]:
#13. Does e equal to a? Why or why not?
e == a
print("")

array([[[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],

       [[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]]])