In [1]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [2]:
#2. Print the NUMPY version and the configuration.
print(np.__version__)
print(np.show_config())

1.15.4
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ricar/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/ricar/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ricar/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib'

In [5]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a = np.random.random((2,3,5))

In [6]:
#4. Print a.
print(a)

[[[0.4765546  0.59297154 0.14883241 0.50716085 0.12856414]
  [0.43375467 0.93820053 0.8115889  0.12741009 0.52939264]
  [0.20022407 0.01457375 0.38379657 0.28281042 0.93291511]]

 [[0.58974605 0.69993477 0.3420701  0.44021727 0.07249797]
  [0.54088508 0.95381975 0.61522473 0.2629829  0.19240723]
  [0.35276961 0.78992258 0.56059734 0.25548015 0.70172535]]]


In [7]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b = np.ones((5,2,3))

In [8]:
#6. Print b.
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [12]:
#7. Do a and b have the same size? How do you prove that in Python code?
# No:
a.shape == b.shape

False

In [15]:
#8. Are you able to add a and b? Why or why not?
print(a.shape)
print(b.shape)
No pueden sumarse a y b porque no tienen el mismo tamaño.

(2, 3, 5)
(5, 2, 3)


In [21]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe
# "c".
c = np.transpose(b, (1,2,0))

In [22]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d = np.add(a, c)
# Funciona porque d tiene el mismo tamaño que a:
print(a.shape)
print(c.shape)

(2, 3, 5)
(2, 3, 5)


In [23]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)
print(d)
# Hay una relación directa entre los valores de ambos arrays. Los valores de d suman 1 a los valores de a.

[[[0.4765546  0.59297154 0.14883241 0.50716085 0.12856414]
  [0.43375467 0.93820053 0.8115889  0.12741009 0.52939264]
  [0.20022407 0.01457375 0.38379657 0.28281042 0.93291511]]

 [[0.58974605 0.69993477 0.3420701  0.44021727 0.07249797]
  [0.54088508 0.95381975 0.61522473 0.2629829  0.19240723]
  [0.35276961 0.78992258 0.56059734 0.25548015 0.70172535]]]
[[[1.4765546  1.59297154 1.14883241 1.50716085 1.12856414]
  [1.43375467 1.93820053 1.8115889  1.12741009 1.52939264]
  [1.20022407 1.01457375 1.38379657 1.28281042 1.93291511]]

 [[1.58974605 1.69993477 1.3420701  1.44021727 1.07249797]
  [1.54088508 1.95381975 1.61522473 1.2629829  1.19240723]
  [1.35276961 1.78992258 1.56059734 1.25548015 1.70172535]]]


In [24]:
#12. Multiply a and c. Assign the result to e.
e = np.multiply(a, c)

In [25]:
#13. Does e equal to a? Why or why not?
e == a
# Sí, porque el 1 es un valor neutro en la multiplicación.

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [27]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max = np.max
d_min = np.min
d_mean = np.mean

In [30]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using
# `np.empty`.
f = np.empty((2,3,5))