In [1]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [2]:
#2. Print the NUMPY version and the configuration.
print(np.version.version)

1.16.2


In [3]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a=np.random.rand(2,3,5)


In [4]:
#4. Print a.
print(a)

[[[0.92098511 0.50997162 0.03964584 0.91050281 0.49523913]
  [0.31522544 0.8869004  0.28662592 0.06526304 0.9751441 ]
  [0.89556557 0.76853779 0.8381115  0.3681627  0.95911879]]

 [[0.17521005 0.78597027 0.45717507 0.21609131 0.30089091]
  [0.23952435 0.7064766  0.22164362 0.13558469 0.61811111]
  [0.66840704 0.19771281 0.97322172 0.08446139 0.17092317]]]


In [5]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b=np.full((5,2,3),1)

In [6]:
#6. Print b.
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [7]:
#7. Do a and b have the same size? How do you prove that in Python code?
print(a.size)
print(b.size)
if a.size==b.size:
    print (True)

30
30
True


In [8]:
#8. Are you able to add a and b? Why or why not?
#print(np.add(a, b))
#No, because they do not have the same shape

In [9]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
print(b.shape)
c = np.transpose(b, (1, 2, 0))
print(c)
print(c.shape)

(5, 2, 3)
[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
(2, 3, 5)


In [10]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d=np.add(a, c)
print(d)
#Because now they do have the same shape

[[[1.92098511 1.50997162 1.03964584 1.91050281 1.49523913]
  [1.31522544 1.8869004  1.28662592 1.06526304 1.9751441 ]
  [1.89556557 1.76853779 1.8381115  1.3681627  1.95911879]]

 [[1.17521005 1.78597027 1.45717507 1.21609131 1.30089091]
  [1.23952435 1.7064766  1.22164362 1.13558469 1.61811111]
  [1.66840704 1.19771281 1.97322172 1.08446139 1.17092317]]]


In [11]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)
print(a.shape)
print(d)
print(d.shape)

#Yes,d is a plus 1

[[[0.92098511 0.50997162 0.03964584 0.91050281 0.49523913]
  [0.31522544 0.8869004  0.28662592 0.06526304 0.9751441 ]
  [0.89556557 0.76853779 0.8381115  0.3681627  0.95911879]]

 [[0.17521005 0.78597027 0.45717507 0.21609131 0.30089091]
  [0.23952435 0.7064766  0.22164362 0.13558469 0.61811111]
  [0.66840704 0.19771281 0.97322172 0.08446139 0.17092317]]]
(2, 3, 5)
[[[1.92098511 1.50997162 1.03964584 1.91050281 1.49523913]
  [1.31522544 1.8869004  1.28662592 1.06526304 1.9751441 ]
  [1.89556557 1.76853779 1.8381115  1.3681627  1.95911879]]

 [[1.17521005 1.78597027 1.45717507 1.21609131 1.30089091]
  [1.23952435 1.7064766  1.22164362 1.13558469 1.61811111]
  [1.66840704 1.19771281 1.97322172 1.08446139 1.17092317]]]
(2, 3, 5)


In [12]:
#12. Multiply a and c. Assign the result to e.
e=a*c
print(e)

[[[0.92098511 0.50997162 0.03964584 0.91050281 0.49523913]
  [0.31522544 0.8869004  0.28662592 0.06526304 0.9751441 ]
  [0.89556557 0.76853779 0.8381115  0.3681627  0.95911879]]

 [[0.17521005 0.78597027 0.45717507 0.21609131 0.30089091]
  [0.23952435 0.7064766  0.22164362 0.13558469 0.61811111]
  [0.66840704 0.19771281 0.97322172 0.08446139 0.17092317]]]


In [13]:
#13. Does e equal to a? Why or why not?
if (e==a).all(): 
    print(True)
else: 
    print(False)
#because a*1=a

True


In [14]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max=np.amax(d)
print(d_max)
d_min=np.amin(d)
print (d_min)
d_mean=np.mean(d)
print(d_mean)

1.9751440988033204
1.039645843888139
1.506213461697023


In [15]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f=np.empty((2,3,5))
print(f)

[[[0.92098511 0.50997162 0.03964584 0.91050281 0.49523913]
  [0.31522544 0.8869004  0.28662592 0.06526304 0.9751441 ]
  [0.89556557 0.76853779 0.8381115  0.3681627  0.95911879]]

 [[0.17521005 0.78597027 0.45717507 0.21609131 0.30089091]
  [0.23952435 0.7064766  0.22164362 0.13558469 0.61811111]
  [0.66840704 0.19771281 0.97322172 0.08446139 0.17092317]]]


In [16]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""
for i in d[:,:,:]:
    for l in i[:]:
        for j in l:
            x=np.where(d==j)[0][0]
            y= np.where(d==j)[1][0]
            z= np.where(d==j)[2][0]
            if j>d_min and j<d_mean:
                f[x,y,z]=25
            elif j>d_mean and j<d_max:
                f[x,y,z]=75
            elif j==d_mean:
                f[x,y,z]=50
            elif j==d_min:
                f[x,y,z]=0
            elif j==d_max:
                f[x,y,z]=100
print(f)

        

[[[ 75.  75.   0.  75.  25.]
  [ 25.  75.  25.  25. 100.]
  [ 75.  75.  75.  25.  75.]]

 [[ 25.  75.  25.  25.  25.]
  [ 25.  75.  25.  25.  75.]
  [ 75.  25.  75.  25.  25.]]]


In [17]:
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""
print(d)
print(f)
#Yes, I have my expected f

[[[1.92098511 1.50997162 1.03964584 1.91050281 1.49523913]
  [1.31522544 1.8869004  1.28662592 1.06526304 1.9751441 ]
  [1.89556557 1.76853779 1.8381115  1.3681627  1.95911879]]

 [[1.17521005 1.78597027 1.45717507 1.21609131 1.30089091]
  [1.23952435 1.7064766  1.22164362 1.13558469 1.61811111]
  [1.66840704 1.19771281 1.97322172 1.08446139 1.17092317]]]
[[[ 75.  75.   0.  75.  25.]
  [ 25.  75.  25.  25. 100.]
  [ 75.  75.  75.  25.  75.]]

 [[ 25.  75.  25.  25.  25.]
  [ 25.  75.  25.  25.  75.]
  [ 75.  25.  75.  25.  25.]]]


In [1]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""

'\n#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values \n("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:\narray([[[ \'D\',  \'D\',  \'D\',  \'B\',  \'D\'],\n        [ \'D\',  \'D\',  \'B\',  \'B\',  \'B\'],\n        [ \'D\',  \'B\',  \'D\',  \'D\',  \'D\']],\n\n       [[ \'B\',  \'B\',  \'B\',  \'B\',  \'E\'],\n        [ \'D\',  \'D\',  \'D\',  \'D\',  \'D\'],\n        [ \'B\',  \'D\',   \'A\',  \'D\', \'D\']]])\nAgain, you don\'t need Numpy in this question.\n'