In [31]:
import numpy as np

In [32]:
print(np.version.version)

1.16.2


In [33]:
a=np.random.rand(2,3,5)
print(a)

[[[0.38630563 0.39978957 0.83226628 0.79918764 0.38006256]
  [0.79474936 0.75308878 0.8702721  0.92219956 0.38618723]
  [0.1762507  0.6384198  0.66115038 0.83107821 0.59301724]]

 [[0.83873188 0.9486791  0.71676915 0.2755627  0.62050999]
  [0.10261962 0.38155323 0.19338313 0.24909099 0.69791527]
  [0.04618378 0.55879839 0.24743238 0.98070713 0.93589514]]]


In [34]:
b = np.full((5,2,3),1)
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [49]:
a_size=a.size
b_size=b.size
if a_size == b_size:
    print("Equal")

Equal


In [55]:
np.transpose(b(2,3,5)).reshape
print(b.shape)

TypeError: 'numpy.ndarray' object is not callable