In [31]:
import numpy as np

In [32]:
print(np.version.version)

1.16.2


In [33]:
a=np.random.rand(2,3,5)
print(a)

[[[0.38630563 0.39978957 0.83226628 0.79918764 0.38006256]
  [0.79474936 0.75308878 0.8702721  0.92219956 0.38618723]
  [0.1762507  0.6384198  0.66115038 0.83107821 0.59301724]]

 [[0.83873188 0.9486791  0.71676915 0.2755627  0.62050999]
  [0.10261962 0.38155323 0.19338313 0.24909099 0.69791527]
  [0.04618378 0.55879839 0.24743238 0.98070713 0.93589514]]]


In [34]:
b = np.full((5,2,3),1)
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [49]:
a_size=a.size
b_size=b.size
if a_size == b_size:
    print("Equal")

Equal


In [58]:
c=b.transpose(1,2,0)
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [61]:
d=np.add(a,c)
print(d)

[[[1.38630563 1.39978957 1.83226628 1.79918764 1.38006256]
  [1.79474936 1.75308878 1.8702721  1.92219956 1.38618723]
  [1.1762507  1.6384198  1.66115038 1.83107821 1.59301724]]

 [[1.83873188 1.9486791  1.71676915 1.2755627  1.62050999]
  [1.10261962 1.38155323 1.19338313 1.24909099 1.69791527]
  [1.04618378 1.55879839 1.24743238 1.98070713 1.93589514]]]


In [62]:
print(a)
print(d)

[[[0.38630563 0.39978957 0.83226628 0.79918764 0.38006256]
  [0.79474936 0.75308878 0.8702721  0.92219956 0.38618723]
  [0.1762507  0.6384198  0.66115038 0.83107821 0.59301724]]

 [[0.83873188 0.9486791  0.71676915 0.2755627  0.62050999]
  [0.10261962 0.38155323 0.19338313 0.24909099 0.69791527]
  [0.04618378 0.55879839 0.24743238 0.98070713 0.93589514]]]
[[[1.38630563 1.39978957 1.83226628 1.79918764 1.38006256]
  [1.79474936 1.75308878 1.8702721  1.92219956 1.38618723]
  [1.1762507  1.6384198  1.66115038 1.83107821 1.59301724]]

 [[1.83873188 1.9486791  1.71676915 1.2755627  1.62050999]
  [1.10261962 1.38155323 1.19338313 1.24909099 1.69791527]
  [1.04618378 1.55879839 1.24743238 1.98070713 1.93589514]]]


In [63]:
e=np.multiply(a,c)
print(e)

[[[0.38630563 0.39978957 0.83226628 0.79918764 0.38006256]
  [0.79474936 0.75308878 0.8702721  0.92219956 0.38618723]
  [0.1762507  0.6384198  0.66115038 0.83107821 0.59301724]]

 [[0.83873188 0.9486791  0.71676915 0.2755627  0.62050999]
  [0.10261962 0.38155323 0.19338313 0.24909099 0.69791527]
  [0.04618378 0.55879839 0.24743238 0.98070713 0.93589514]]]


In [64]:
d_mean=np.mean(d)
d_min=np.min(d)
d_max=np.max(d)
print(d_mean)
print(d_min)
print(d_max)

1.5739285632535187
1.0461837769015885
1.9807071349570982


In [66]:
f=np.empty((2,3,5))
print(f)

[[[0.38630563 0.39978957 0.83226628 0.79918764 0.38006256]
  [0.79474936 0.75308878 0.8702721  0.92219956 0.38618723]
  [0.1762507  0.6384198  0.66115038 0.83107821 0.59301724]]

 [[0.83873188 0.9486791  0.71676915 0.2755627  0.62050999]
  [0.10261962 0.38155323 0.19338313 0.24909099 0.69791527]
  [0.04618378 0.55879839 0.24743238 0.98070713 0.93589514]]]


In [71]:
for i in range(f.shape[0]):
    for ii in range(f.shape[1]):
        for iii in range (f.shape[2]):
            if d[i,ii,iii]>d_min and d[i,ii,iii]<d_mean:
                f[i,ii,iii]=25
            elif d[i,ii,iii]>d_mean and d[i,ii,iii]<d_max:
                f[i,ii,iii]=75
            elif d[i,ii,iii]==d_mean:
                f[i,ii,iii]=50
            elif d[i,ii,iii]==d_min:
                f[i,ii,iii]=0
            elif d[i,ii,iii]==d_max:
                f[i,ii,iii]=100
print(f)

[[[ 25.  25.  75.  75.  25.]
  [ 75.  75.  75.  75.  25.]
  [ 25.  75.  75.  75.  75.]]

 [[ 75.  75.  75.  25.  75.]
  [ 25.  25.  25.  25.  75.]
  [  0.  25.  25. 100.  75.]]]
