In [1]:
#1. Import the NUMPY package under the name np.

import numpy as np

In [2]:
np.version.version

'1.16.2'

In [3]:
a = np.random.random((2,3,5))
print(a)

[[[0.47592502 0.13611024 0.46396332 0.61691147 0.7120992 ]
  [0.80819878 0.23626634 0.27663945 0.65025424 0.74353673]
  [0.76667668 0.77089386 0.45803839 0.65992756 0.07786613]]

 [[0.53674063 0.22122071 0.88866233 0.42863905 0.65826686]
  [0.60124757 0.77324343 0.3704526  0.26047368 0.38688279]
  [0.03971415 0.18761548 0.4947753  0.84556098 0.9081654 ]]]


In [14]:
b= np.ones((5,2,3)*1)


In [15]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [16]:
print(a.size)
print(b.size)
if (a.size) == b.size:
    print("son iguales")
else:
    print ("son distintos")

30
30
son iguales


In [20]:
c = np.ones_like(a) 
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [18]:
print(c.shape)

(2, 3, 5)


In [28]:
c =np.transpose(b,(1,2,0))


In [29]:
print(c.shape)

(2, 3, 5)


In [31]:
d = a +c

In [32]:
print(d)

[[[1.47592502 1.13611024 1.46396332 1.61691147 1.7120992 ]
  [1.80819878 1.23626634 1.27663945 1.65025424 1.74353673]
  [1.76667668 1.77089386 1.45803839 1.65992756 1.07786613]]

 [[1.53674063 1.22122071 1.88866233 1.42863905 1.65826686]
  [1.60124757 1.77324343 1.3704526  1.26047368 1.38688279]
  [1.03971415 1.18761548 1.4947753  1.84556098 1.9081654 ]]]


In [58]:
a == d
print("la suma de los valores de a ( " + str(np.sum(a)) + " )es distinta a la suma de los valores de d (" + str(np.sum(c)) +")")

la suma de los valores de a ( 15.454968378418418 )es distinta a la suma de los valores de d (30.0)


In [45]:
e = a* c

In [47]:
print(e)
print(a)

[[[0.47592502 0.13611024 0.46396332 0.61691147 0.7120992 ]
  [0.80819878 0.23626634 0.27663945 0.65025424 0.74353673]
  [0.76667668 0.77089386 0.45803839 0.65992756 0.07786613]]

 [[0.53674063 0.22122071 0.88866233 0.42863905 0.65826686]
  [0.60124757 0.77324343 0.3704526  0.26047368 0.38688279]
  [0.03971415 0.18761548 0.4947753  0.84556098 0.9081654 ]]]
[[[0.47592502 0.13611024 0.46396332 0.61691147 0.7120992 ]
  [0.80819878 0.23626634 0.27663945 0.65025424 0.74353673]
  [0.76667668 0.77089386 0.45803839 0.65992756 0.07786613]]

 [[0.53674063 0.22122071 0.88866233 0.42863905 0.65826686]
  [0.60124757 0.77324343 0.3704526  0.26047368 0.38688279]
  [0.03971415 0.18761548 0.4947753  0.84556098 0.9081654 ]]]


In [48]:
a == e

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [53]:
d_max= d.max()
d_min= d.min()
d_mean= d.mean()

In [54]:
print(d_max, d_min, d_mean)

1.9081654029738093 1.0397141458954116 1.5151656126139474


In [63]:
f = np.empty((2,3,5))

In [78]:
for x in range(len(d)):
    for y in range(len(d[x])):
        for z in range(len(d[x][y])):
            if d[x][y][z] == d_min:
                   d[x][y][z] = 0
            elif d_min < d[x][y][z] < d_mean:
                   d[x][y][z] = 25
            elif d[x][y][z] == d_mean:
                   d[x][y][z] = 50
            elif d[x][y][z] < d_max:
                   d[x][y][z] = 75
            else:
                   d[x][y][z]= 100
    
    