In [30]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.multiclass import OneVsOneClassifier, OneVsRestClassifier
#from sklearn.preprocessing import LabelEncoder

from sklearn.metrics import accuracy_score, log_loss
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC, LinearSVC, NuSVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

In [4]:
columnNames= [
    'id number',
    'Clump Thickness',
    'Uniformity of Cell Size',
    'Uniformity of Cell Shape',
    'Marginal Adhesion',
    'Single Epithelial Cell Size',
    'Bare Nuclei',
    'Bland Chromatin',
    'Normal Nucleoli',
    'Mitoses',
    'Class']                        
#(2 for benign, 4 for malignant)

In [15]:
df =  pd.read_csv('breast-cancer-wisconsin.data.txt', header= None, names= columnNames)

In [16]:
df.head()

id number  Clump Thickness  Uniformity of Cell Size  \
0    1000025                5                        1   
1    1002945                5                        4   
2    1015425                3                        1   
3    1016277                6                        8   
4    1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

  Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0           1                3                1        1      2  
1          10                3                2        1      2  
2           2                3                1        1      2  
3           4                3                7        1      2  
4           1                3                1        1      2

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 11 columns):
id number                      699 non-null int64
Clump Thickness                699 non-null int64
Uniformity of Cell Size        699 non-null int64
Uniformity of Cell Shape       699 non-null int64
Marginal Adhesion              699 non-null int64
Single Epithelial Cell Size    699 non-null int64
Bare Nuclei                    699 non-null object
Bland Chromatin                699 non-null int64
Normal Nucleoli                699 non-null int64
Mitoses                        699 non-null int64
Class                          699 non-null int64
dtypes: int64(10), object(1)
memory usage: 60.1+ KB


In [18]:
df['Bare Nuclei'].value_counts()

1     402
10    132
5      30
2      30
3      28
8      21
4      19
?      16
9       9
7       8
6       4
Name: Bare Nuclei, dtype: int64

In [27]:
# He leido que en casos como este se pone un valor negativo enorme para que no se tenga en cuenta
# y no perder los datos del paciente.
df['Bare Nuclei'].replace('?', -99999, inplace= True)
df['Bare Nuclei']= df['Bare Nuclei'].astype('int64')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 11 columns):
id number                      699 non-null int64
Clump Thickness                699 non-null int64
Uniformity of Cell Size        699 non-null int64
Uniformity of Cell Shape       699 non-null int64
Marginal Adhesion              699 non-null int64
Single Epithelial Cell Size    699 non-null int64
Bare Nuclei                    699 non-null int64
Bland Chromatin                699 non-null int64
Normal Nucleoli                699 non-null int64
Mitoses                        699 non-null int64
Class                          699 non-null int64
dtypes: int64(11)
memory usage: 60.1 KB


In [37]:
X=df.drop(['id number', 'Class'], axis=1)
y=df['Class']

In [50]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [51]:
knClf= KNeighborsClassifier()
knClf.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [52]:
y_predict= knClf.predict(X_test)

In [55]:
confusion_matrix(y_test, y_predict)

array([[92,  1],
       [ 2, 45]])

In [53]:
accuracy_score(y_test, y_predict)

0.9785714285714285

In [81]:
#Pasar la serie al formato necesario de array para predict.
sujetoBenigno= X_test.iloc[2].values.reshape(1, -1)
sujeto

array([[2, 1, 1, 1, 2, 1, 2, 1, 1]])

In [82]:
sujetoMaligno= [[5,4,4,5,7,10,3,2,1]]

In [84]:
value_predict= knClf.predict(sujetoMaligno)
value_predict

array([4])

In [ ]:
'''
Ideas de 10 classifier showdown
'''

In [ ]:
classifiers = [
    KNeighborsClassifier(3),
    SVC(kernel="rbf", C=0.025, probability=True),
    NuSVC(probability=True),
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    AdaBoostClassifier(),
    GradientBoostingClassifier(),
    GaussianNB(),
    LinearDiscriminantAnalysis(),
    QuadraticDiscriminantAnalysis()]

In [ ]:
# Logging for Visual Comparison
log_cols=["Classifier", "Accuracy", "Log Loss"]
log = pd.DataFrame(columns=log_cols)

for clf in classifiers:
    clf.fit(X_train, y_train)
    name = clf.__class__.__name__
    
    print("="*30)
    print(name)
    
    print('****Results****')
    y_predict = clf.predict(X_test)
    acc = accuracy_score(y_test, y_predict)
    print("Accuracy: {:.4%}".format(acc))
    
    y_predict = clf.predict_proba(X_test)
    ll = log_loss(y_test, y_predict)
    print("Log Loss: {}".format(ll))
    
    log_entry = pd.DataFrame([[name, acc*100, ll]], columns=log_cols)
    log = log.append(log_entry)
    
print("="*30)

In [ ]:
'''
Fichero de Marc pasa sacar ideas.
Diccionario de clasificadores.
'''

In [ ]:
import pandas as pd
df_train = pd.read_csv("~/Downloads/titanic/train.csv")
df_test = pd.read_csv("~/Downloads/titanic/test.csv")

X_train = pd.get_dummies(df_train[["Sex","Age","SibSp","Parch","Fare","Embarked"]],columns=["Embarked","Sex"], drop_first=True).fillna(0)
y_train = df_train[["Pclass"]]["Pclass"]

X_test= pd.get_dummies(df_test[["Sex","Age","SibSp","Parch","Fare","Embarked"]],columns=["Embarked","Sex"], drop_first=True).fillna(0)
y_test = df_test[["Pclass"]]["Pclass"]


display(X_train.head(),y_train.head())
display(X_test.head(),y_test.head())


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.multiclass import OneVsOneClassifier, OneVsRestClassifier
from sklearn.ensemble import RandomForestClassifier

# Models
svmCLS = SVC(kernel="sigmoid",probability=True, gamma="auto", C=100)
lsrCLS = LogisticRegression(solver="lbfgs", max_iter=1000)
rforest = RandomForestClassifier(n_estimators=10)
rforest50 = RandomForestClassifier(n_estimators=20)

# Strategies
classifiers = [
    {"name":"SVM-v1 1v1", "cls": OneVsOneClassifier(svmCLS) },
    {"name":"Logistic 1v1", "cls": OneVsOneClassifier(lsrCLS) },
    {"name":"RandomForest 1v1", "cls": OneVsOneClassifier(rforest) },
    {"name":"SVM-v1 1v-all", "cls": OneVsRestClassifier(svmCLS) },
    {"name":"Logistic 1v-all", "cls": OneVsRestClassifier(lsrCLS) },
    {"name":"RandomForest 1v-all", "cls": OneVsRestClassifier(rforest) },
    {"name":"RandomForest50 1v-all", "cls": OneVsRestClassifier(rforest50) }
]

# Train Phase
for cls in classifiers:
    classifier = cls["cls"]
    clsName = cls["name"]
    classifier.fit(X_train, y_train)
    score = classifier.score(X_test, y_test)
    print("{}\t\t{}".format(score,clsName))

In [ ]:
import matplotlib.pyplot as plt
from sklearn.utils.multiclass import unique_labels
import numpy as np

def plot_confusion_matrix(y_true, y_pred, classes,
                          normalize=False,
                          title=None,
                          cmap=plt.cm.Blues):
    """
    This function prints and plots the confusion matrix.
    Normalization can be applied by setting `normalize=True`.
    """
    if not title:
        if normalize:
            title = 'Normalized confusion matrix'
        else:
            title = 'Confusion matrix, without normalization'

    # Compute confusion matrix
    cm = confusion_matrix(y_true, y_pred)
    # Only use the labels that appear in the data
    classes = classes[unique_labels(y_true, y_pred)]
    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('Confusion matrix, without normalization')

    print(cm)

    fig, ax = plt.subplots()
    im = ax.imshow(cm, interpolation='nearest', cmap=cmap)
    ax.figure.colorbar(im, ax=ax)
    # We want to show all ticks...
    ax.set(xticks=np.arange(cm.shape[1]),
           yticks=np.arange(cm.shape[0]),
           # ... and label them with the respective list entries
           xticklabels=classes, yticklabels=classes,
           title=title,
           ylabel='True label',
           xlabel='Predicted label')

    # Rotate the tick labels and set their alignment.
    plt.setp(ax.get_xticklabels(), rotation=45, ha="right",
             rotation_mode="anchor")

    # Loop over data dimensions and create text annotations.
    fmt = '.2f' if normalize else 'd'
    thresh = cm.max() / 2.
    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            ax.text(j, i, format(cm[i, j], fmt),
                    ha="center", va="center",
                    color="white" if cm[i, j] > thresh else "black")
    fig.tight_layout()
    return ax

In [ ]:
from sklearn.metrics import confusion_matrix

rf = classifiers[-1]["cls"]
y_predict = rf.predict(X_test)
classes = pd.Series(index=set(y_test),data=["clase1","clase2","clase3"])
print(y_train.value_counts())
plot_confusion_matrix(y_test,y_predict,classes, normalize=True)