In [1]:
#1. Import the NUMPY package under the name np.
import numpy as np
#2. Print the NUMPY version and the configuration.
print(np.version.version)

1.16.2


In [2]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a=np.random.rand(2,3,5)
#4. Print a.
print(a)

[[[0.26859739 0.32336878 0.93140613 0.76971284 0.20211542]
  [0.48104205 0.15521933 0.58840303 0.47796366 0.74947483]
  [0.29875963 0.21128101 0.3219035  0.79941112 0.87482475]]

 [[0.91573349 0.98323431 0.08876742 0.8877565  0.44576084]
  [0.71755586 0.38958529 0.44368898 0.77874435 0.17729445]
  [0.85049577 0.07109678 0.91582117 0.51552977 0.05482297]]]


In [3]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b=np.full((5,2,3),1)
#6. Print b.
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [4]:
#7. Do a and b have the same size? How do you prove that in Python code?
print(a.size)
print(b.size)
if a.size==b.size:
    print (True)

30
30
True


In [5]:
#8. Are you able to add a and b? Why or why not?
print(np.add(a, b))
#No, because they do not have the same shape

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [6]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
print(b.shape)
c = np.transpose(b, (1, 2, 0))
print(c)
print(c.shape)

(5, 2, 3)
[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
(2, 3, 5)


In [7]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d=np.add(a, c)
print(d)
#Because now they do have the same shape

[[[1.26859739 1.32336878 1.93140613 1.76971284 1.20211542]
  [1.48104205 1.15521933 1.58840303 1.47796366 1.74947483]
  [1.29875963 1.21128101 1.3219035  1.79941112 1.87482475]]

 [[1.91573349 1.98323431 1.08876742 1.8877565  1.44576084]
  [1.71755586 1.38958529 1.44368898 1.77874435 1.17729445]
  [1.85049577 1.07109678 1.91582117 1.51552977 1.05482297]]]


In [8]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)
print(a.shape)
print(d)
print(d.shape)
#Yes,d is a plus 1

[[[0.26859739 0.32336878 0.93140613 0.76971284 0.20211542]
  [0.48104205 0.15521933 0.58840303 0.47796366 0.74947483]
  [0.29875963 0.21128101 0.3219035  0.79941112 0.87482475]]

 [[0.91573349 0.98323431 0.08876742 0.8877565  0.44576084]
  [0.71755586 0.38958529 0.44368898 0.77874435 0.17729445]
  [0.85049577 0.07109678 0.91582117 0.51552977 0.05482297]]]
(2, 3, 5)
[[[1.26859739 1.32336878 1.93140613 1.76971284 1.20211542]
  [1.48104205 1.15521933 1.58840303 1.47796366 1.74947483]
  [1.29875963 1.21128101 1.3219035  1.79941112 1.87482475]]

 [[1.91573349 1.98323431 1.08876742 1.8877565  1.44576084]
  [1.71755586 1.38958529 1.44368898 1.77874435 1.17729445]
  [1.85049577 1.07109678 1.91582117 1.51552977 1.05482297]]]
(2, 3, 5)


In [9]:
#12. Multiply a and c. Assign the result to e.
e=a*c
print(e)

[[[0.26859739 0.32336878 0.93140613 0.76971284 0.20211542]
  [0.48104205 0.15521933 0.58840303 0.47796366 0.74947483]
  [0.29875963 0.21128101 0.3219035  0.79941112 0.87482475]]

 [[0.91573349 0.98323431 0.08876742 0.8877565  0.44576084]
  [0.71755586 0.38958529 0.44368898 0.77874435 0.17729445]
  [0.85049577 0.07109678 0.91582117 0.51552977 0.05482297]]]


In [10]:
#13. Does e equal to a? Why or why not?
if (e==a).all(): 
    print(True)
else: 
    print(False)
#Yes, because a*1=a

True


In [11]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max=np.amax(d)
print(d_max)
d_min=np.amin(d)
print (d_min)
d_mean=np.mean(a)
print(d_mean)

1.983234307512081
1.0548229670718734
0.5229790470489838


In [12]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f=np.empty((2,3,5))
print(f)

[[[0.26859739 0.32336878 0.93140613 0.76971284 0.20211542]
  [0.48104205 0.15521933 0.58840303 0.47796366 0.74947483]
  [0.29875963 0.21128101 0.3219035  0.79941112 0.87482475]]

 [[0.91573349 0.98323431 0.08876742 0.8877565  0.44576084]
  [0.71755586 0.38958529 0.44368898 0.77874435 0.17729445]
  [0.85049577 0.07109678 0.91582117 0.51552977 0.05482297]]]


In [27]:
"""#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, 
assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""
for i in d[:,:,:]:
    for f in i[:]:
        for j in f:
            if j>d_min and j<d_mean:
                f[np.where(d==j)[0][0],np.where(d==j)[1][0],np.where(d==j)[2][0]]=f[np.where(d==j)[0][0],np.where(d==j)[1][0],np.where(d==j)[2][0]]+25
            elif j>d_mean and j<d_max:
                f[np.where(d==j)[0][0],np.where(d==j)[1][0],np.where(d==j)[2][0]]=f[np.where(d==j)[0][0],np.where(d==j)[1][0],np.where(d==j)[2][0]]+75
            elif j==d_mean:
                f[np.where(d==j)[0][0],np.where(d==j)[1][0],np.where(d==j)[2][0]]=f[np.where(d==j)[0][0],np.where(d==j)[1][0],np.where(d==j)[2][0]]+50
            elif j==d_min:
                f[np.where(d==j)[0][0],np.where(d==j)[1][0],np.where(d==j)[2][0]]=f[np.where(d==j)[0][0],np.where(d==j)[1][0],np.where(d==j)[2][0]]+0
            elif j==d_max:
                f[np.where(d==j)[0][0],np.where(d==j)[1][0],np.where(d==j)[2][0]]=f[np.where(d==j)[0][0],np.where(d==j)[1][0],np.where(d==j)[2][0]]+100
print(b)

IndexError: too many indices for array