In [2]:
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn import datasets
from sklearn.decomposition import PCA

# import some data to play with
iris = datasets.load_iris()

In [7]:
X = iris.data
y = iris.target
print(X.shape, y.shape)


(150, 4) (150,)


In [45]:
import numpy as np
from sklearn import svm
from sklearn.model_selection import cross_val_score
#clf = svm.SVC(gamma="auto")
clf = LogisticRegression(solver='lbfgs', multi_class="auto")
scores = cross_val_score(clf, X, y, cv=5)
np.mean(scores)

/usr/local/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


0.9733333333333334

In [46]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
#clf = svm.SVC(gamma="auto")
clf = LogisticRegression(solver='lbfgs', multi_class="auto")


X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

# Train the SVC model
clf.fit(X_train,y_train)
print(clf.coef_)


[[-0.48507171  0.83270217 -2.36899093 -1.00112418]
 [ 0.43943807 -0.32787005 -0.2267952  -0.82046691]
 [ 0.04563364 -0.50483212  2.59578613  1.82159109]]


/usr/local/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


In [47]:
import pandas as pd
prediction_result = clf.predict(X_test)
groundtruth = y_test

df = pd.DataFrame([prediction_result, groundtruth]).T
df.columns = ["PRED","GT"]

df



PRED  GT
0      0   0
1      1   1
2      1   1
3      0   0
4      1   1
5      1   1
6      0   0
7      2   2
8      1   1
9      0   0
10     0   0
11     1   2
12     0   0
13     0   0
14     2   2
15     2   2
16     0   0
17     0   0
18     0   0
19     0   0
20     2   2
21     1   1
22     0   0
23     2   2
24     2   2
25     2   2
26     2   2
27     0   0
28     0   0
29     1   1

In [48]:
clf.predict([[2, 1.1, 3, 5]])

array([2])